miseq_path <- file.path()
filt_path <- file.path()
fns <- NULL
fnFs <- NULL
fnRs <- NULL
ii <- NULL
derepFs <- NULL
derepRs <- NULL
sam.names <- NULL
ddF <- NULL
ddR <- NULL
dadaFs <- NULL
dadaRs <- NULL
seqtab.all <- NULL
seqtab <- NULL
ref_fasta <- NULL
taxtab <- NULL
seqs <- NULL
alignment <- NULL
phang.align <- NULL
dm <- NULL
treeNJ <- NULL
fit = NULL
fitGTR <- NULL
mergers <- NULL
mimarks_path <- NULL
samdf <- NULL
samdf <- NULL
ps <- NULL
